### VSCode Extention: Rest Client
### RS     - 108.48.52.183:7061
### ZN     - 112.17.170.154:7061
### ttdata - ixinbuy.com:7061

### Registration
POST {{host}}:{{port}}/register
content-type: application/json

{
    "device_id": "test-med-51501",
	"category": "testing"
}

### Upload data
POST {{host}}:{{port}}/uploaddata
content-type: application/json
appkey: <appkey>

{
    "data_type": 1, 
    "device_id": "test-med-51501", 
    "key": "",
	"required_field": "issur|owner",
	"device_data": [
		{
			"datetime": "2020-03-23T01:01:01",
			"issuer": "lab1",
			"owner": "renshan",
			"med_data": {
				"temperature": 36.5,
				"heart_rate": 76,
				"glucose": 101,
				"blood_pressure": {
					"high": 130,
					"low": 70
				}
			}
		},
		{
			"datetime": "2020-04-21T01:11:01",
			"issuer": "i1",
			"owner": "o2",
			"med_data": {
				"temperature": 36.5,
				"heart_rate": 76,
				"glucose": 101,
				"blood_pressure": {
					"high": 130,
					"low": 70
			    }
            }
		}
	]
}

### Request for sharing
POST {{host}}:{{port}}/requestshare
content-type: application/json

{
	"data_type": 1,
	"device_id":"test-med-51501",
	"owner":"renshan",
	"viewer": "viewer02",
	"fields": "heart_rate, glucose, blood_pressure"
}

### Querydata
GET {{host}}:{{port}}/querydata?data_type=1&device_id=test-med-51501


### Get Shared Data
GET {{host}}:{{port}}/getshareddata?
&data_type=1&device_id=test-med-51501&viewer=viewer02