### VSCode Extention: Rest Client
### Ctrl + Alt + E to change the environment

### Registration
POST {{host}}:{{port}}/register
content-type: application/json

{
    "device_id": "test-51501"
}

### Upload data
POST {{host}}:{{port}}/uploaddata
content-type: application/json

{
    "data_type": 2, 
    "device_id": "test-51501", 
    "key": "date",
    "device_data": 
    [{
        "date": "2001-05-15",
        "last_checked": "2020-05-12T10:43:02",
        "status": "failed"
    }
    ]
}

### Querydata
GET {{host}}:{{port}}/querydata?data_type=2&device_id=test-51501


### Get Shared Data
GET {{host}}:{{port}}/getshareddata?
&data_type=2&device_id=test-51501