### VSCode Extention: Rest Client
### Ctrl + Alt + E to change the environment

### Registration
POST {{host}}:{{port}}/register
content-type: application/json

{
    "device_id": "test-51501",
    "category": "medical"
}

### Upload data
POST {{host}}:{{port}}/uploaddata
content-type: application/json

{
    "data_type": 2, 
    "device_id": "test-51501", 
    "key": "date|country_region|province_state|county|last_update|confirmed",
    "device_data": 
    [ {
        "date": "2020-03-30",
        "country_region": "US",
        "province_state": "New York",
        "county": "Allegany",
        "last_update": "2020-03-10T10:43:02",
        "confirmed": 7,
        "deaths": 1,
        "recovered": 0,
        "latitude": 42.60060306,
        "longitude": -73.97723916
    },
    {
        "date": "2020-04-01",
        "country_region": "US",
        "province_state": "New York",
        "county": "Allegany",
        "last_update": "2020-04-12T10:43:02",
        "confirmed": 10,
        "deaths": 1,
        "recovered": 0,
        "latitude": 42.60060306,
        "longitude": -73.97723916,
        "key": "date|province_state|county|country_region"
    }
    ]
}

### Querydata
GET {{host}}:{{port}}/querydata?data_type=2&device_id=test-51501


### Get Shared Data
GET {{host}}:{{port}}/getshareddata?
&data_type=2&device_id=test-ttdata-20200521&country_region=us&date=2020-03-02|2020-05-22&county=Allegany