### VSCode Extention: Rest Client
### RS     - 108.48.52.183:7061
### ZN     - 112.17.170.154:7061
### ttdata - ixinbuy.com:7061

### Registration
POST {{host}}:{{port}}/register
content-type: application/json

{
    "device_id": "John_Smith1",
	"category": "test"
}

### Upload data
POST {{host}}:{{port}}/uploaddata
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

{
    "data_type": 1, 
    "device_id": "John_Smith1", 
    "key": "",   
	"required_field": "issuer|owner",
	"device_data": [
		{
			"datetime": "2020-03-23T01:01:01",
			"issuer": "lab1",
			"owner": "John Smith",
			"med_data": {
				"temperature": 36.5,
				"heart_rate": 76,
				"glucose": 101,
				"blood_pressure": {
					"high": 130,
					"low": 70
				}
			}
		},
		{
			"datetime": "2020-04-21T01:11:01",
			"issuer": "i1",
			"owner": "o2",
			"med_data": {
				"temperature": 36.5,
				"heart_rate": 76,
				"glucose": 101,
				"blood_pressure": {
					"high": 130,
					"low": 70
			    }
            }
		}
	]
}

### Request for sharing
POST {{host}}:{{port}}/requestshare
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

{
	"data_type": 1,
	"device_id":"John_Smith1",
	"owner":"John Smith",
	"viewer": "Peter",
	"fields": "heart_rate, glucose, blood_pressure"
}
### Viewer request data access from owner
POST {{host}}:{{port}}/requestsharing
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

{
	"data_type": 1,
	"device_id":"John_Smith1",
	"owner":"John Smith",
	"viewer": "Peter",
	"fields": "heart_rate, glucose, blood_pressure"
}
### Owner get pending requests
GET {{host}}:{{port}}/getrequest?
&data_type=1&device_id=John_Smith1&owner=John%20Smith
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

### Owner approve or reject the request 
POST {{host}}:{{port}}/requestapproval
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

{
	"data_type": 1,
	"device_id":"John_Smith1",
	"owner":"John Smith",
	"viewer": "Peter",
	"fields": "heart_rate, glucose, blood_pressure",
	"request_id":"5ffb29e9a4978f144ebcbe87",
	"reuqest_approval":true
}

### Owner get owner's data
GET {{host}}:{{port}}/getownerdata?
&data_type=1&device_id=John_Smith1&owner=John Smith
content-type: application/json
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f


### Get Shared Data
GET {{host}}:{{port}}/getshareddata?
&viewer=Peter&$filter=data_type eq 1 and device_id eq 'John_Smith1'
appkey: 872ba39f0a66fe5dfd4ea4b4e2ce406f8192dd0978a9a3981c70ad845998e53f

